---@class CS.FairyEditor.Component.InputElement : CS.System.ValueType
---@field public name string
---@field public type string
---@field public prop string
---@field public dummy boolean
---@field public extData CS.System.Object
---@field public min CS.FairyEditor.Component.InputElement.OptionalValue_CS.System.Single
---@field public max CS.FairyEditor.Component.InputElement.OptionalValue_CS.System.Single
---@field public step CS.FairyEditor.Component.InputElement.OptionalValue_CS.System.Single
---@field public precision CS.FairyEditor.Component.InputElement.OptionalValue_CS.System.Int32
---@field public items String[]
---@field public values String[]
---@field public isIndex boolean
---@field public inverted boolean
---@field public showAlpha boolean
---@field public filter String[]
---@field public pages string
---@field public includeChildren boolean
---@field public prompt string
---@field public readonly boolean
---@field public disableIME boolean
---@field public trim boolean

---@type CS.FairyEditor.Component.InputElement
CS.FairyEditor.Component.InputElement = { }
